# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 4132:5432
    environment:
      POSTGRES_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 4179:8080